### ISSUE TITLE
StreamEvent(s?)Received

### ISSUE THREAD

**Issue by JefClaes** [damianh/SqlStreamStore#37] opened 2016-09-23 18:43 UTC
When subscribing to a stream, SqlStreamStore starts by reading events you haven't seen yet based on the position you provide. It will then for each event invoke the StreamEventReceived delegate. 

In case you want to remember the last message you've processed, you end up checkpointing (to a database, a file...) after processing each message. Next to checkpointing, each message that you're interested in has a reaction (a DDL statement, publishing to a bus..) with some cost attached to it. 

When your projection is catching up, I think it is beneficial to instead of passing over a single message, to pass over a list of events to the StreamEvent(s)Received received delegate. This would allow to make impactful optimisations in regards to processing of DML statements or dispatching of messages in bulk.

**Comment by damianh** [comment] 2016-09-28 18:40
So you would like to see

    public delegate Task StreamMessageReceived(StreamMessage streamMessage);

be

    public delegate Task StreamMessageReceived(StreamMessage[] streamMessage);

instead?

The current implementation underneath is using paging so this would be possible.  @thefringeninja Would this work for you? Something you'd like to see?

**Comment by damianh** [comment] 2016-09-28 18:41
Actually it would have to be 

    public delegate Task StreamMessagesReceived(StreamMessage[] streamMessage, CancellationToken ct);

... where you would need to participate in co-operative cancellation.

**Comment by yreynhout** [comment] 2016-09-29 08:30
The root cause for this request seems to be that you're aligning your unit of work (on the projection side) with the callback delegate. What if you kept your unit of work (session, batch of statements, etc) around longer, and flush based on a threshold that makes sense for the projection store you are targeting instead of the amount of messages you are projecting. Trying to match page size with that threshold will only work for all but trivial projections anyway. The nasty thing is probably keeping track of state across callback calls. You could provide a method of an object that matches the delegate's signature and track state that way.

**Comment by damianh** [comment] 2016-09-29 09:31
This is easy to do without a change:

    Func<ICollection<StreamMessage>, Task> handleBatch = messages =>
    {
        // Do stuff.
        return Task.CompletedTask;
    };
    var batch = new List<StreamMessage>();
    var subscription = store.SubscribeToAll(null,
        async message =>
        {
            batch.Add(message);
            if(batch.Count == 10)
            {
                await handleBatch(batch);
                batch.Clear();
            }
        });

Could easily put this in an extension method too.

**Comment by JefClaes** [comment] 2016-09-29 22:51
That would work in rebuild/burst scenarios, but batching that way in live/low-ish troughput projections would introduce extra latency, unless you want to go the route of periodical flushes as well.

**Comment by yreynhout** [comment] 2016-09-29 23:14
You could swap the behavior depending on the situation (live vs replay).

**Comment by damianh** [comment] 2016-09-30 05:28
Agreed, my example was a bit crude.

**Comment by damianh** [comment] 2016-09-30 07:27
Something that I feel that is missing from this API (and the `SubscribeToStream`) is giving the subscriber a hint as to how close to the end of the (all) stream the subscription is. Underneath, the implementation is calling `ReadAllForwards` whose `AllMessagesPage` result has an IsEnd hint. I'm thinking that if I can pass that forward and maybe some other context, such as the head position / last stream version _at time of read_, it will aid the subscriber in deciding whether is it catching or caught up.

**Comment by damianh** [comment] 2016-10-12 10:23
The "caught up" callback is here https://github.com/damianh/SqlStreamStore/blob/master/src/SqlStreamStore/IReadonlyStreamStore.cs#L160 

This can be used as a trigger to know when you switch from batch to contiguous (and maybe back again).

I'm not 100% on the current design, but I wanted to ship something that can be played with to get feedback.

**Comment by damianh** [comment] 2016-10-20 20:09
I'm going to close this as I believe the current API allows this scenario (however I think the API can be improved, fine to open new issue with ideas).

**Closed by damianh** 2016-10-20 20:09 UTC
